include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'build-image.template.yaml'
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'helm.template.yaml'

default:
  tags:
    - adcorn-dev

variables:
  APP_NAME: "app"
  APP_NAMESPACE: "${CI_PROJECT_ROOT_NAMESPACE}-${CI_PROJECT_NAME}"
  ENVIRONMENT: dev

stages:
  - build
  - deploy

build:
  stage: build
  extends: .build_image
  variables:
    KUBERNETES_CPU_REQUEST: 500m
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_MEMORY_REQUEST: 2048Mi
    KUBERNETES_MEMORY_LIMIT: 4096Mi
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=development --build-arg REACT_APP_API_URL=https://backend-dev.defihelper.info/api --build-arg REACT_APP_LAUNCH_APP_URL=https://app-dev.defihelper.info/"
    - if: $CI_COMMIT_REF_NAME == "release"
      variables:
        BUILD_ARGS: "--build-arg NODE_ENV=production --build-arg REACT_APP_API_URL=https://backend.defihelper.io/api --build-arg REACT_APP_LAUNCH_APP_URL=https://app.defihelper.io/"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

deploy:
  extends: .helm_upgrade
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "release"'
