include:
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'build-image.template.yaml'
  - project: 'devops/gitlab-ci-templates'
    ref: master
    file: 'helm.template.yaml'

default:
  tags:
    - adcorn-dev

variables:
  APP_NAME: "website"
  APP_NAMESPACE: website

stages:
  - build
  - deploy

build:
  stage: build
  extends: .build_image
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH'

deploy:
  extends: .helm_upgrade
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "release"'