overwrite: true
schema: "https://backend-dev.defihelper.info/api"
documents: [
  './src/**/**/*.graphql.ts',
]
config:
  scalars:
    AddressType: string
    DateTimeType: string
generates:
  src/graphql/_generated-fragment-types.ts:
    plugins:
      - add:
          content: '/* eslint-disable */'
      - fragment-matcher
  src/graphql/_generated-types.ts:
    plugins:
      - add:
          content: '/* eslint-disable */'
      - typescript
      - typescript-operations
  src/graphql/_generated-hooks.tsx:
    plugins:
      - add:
          content: '/* eslint-disable */'
      - typescript
      - typescript-operations
      - typescript-urql
    config:
      urqlImportFrom: "urql"
      withComponent: false
      withHOC: false
      withHooks: true
hooks:
  afterAllFileWrite:
    - prettier --write
