name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - if: github.event.release.prerelease == true
        run: npm run build-dev
        env:
          REACT_APP_PORTIS_ID:
          REACT_APP_API_URL: https://backend.defi-helper.com/api
          REACT_APP_SENTRY:
          REACT_APP_TREZOR_URL:
          REACT_APP_TREZOR_EMAIL:
          REACT_APP_FORTMATIC_KEY:
          REACT_APP_WAVES_NODE_URL: https://nodes.wavesnodes.com
          REACT_APP_SID_LIFE_TIME: 31536000
          REACT_APP_ADAPTERS_HOST: https://backend.defi-helper.com/adapters
      - if: github.event.release.prerelease == false
        run: npm run build
        env:
          REACT_APP_PORTIS_ID:
          REACT_APP_API_URL: https://backend.defihelper.io/api
          REACT_APP_SENTRY:
          REACT_APP_TREZOR_URL:
          REACT_APP_TREZOR_EMAIL:
          REACT_APP_FORTMATIC_KEY:
          REACT_APP_WAVES_NODE_URL: https://nodes.wavesnodes.com
          REACT_APP_SID_LIFE_TIME: 31536000
          REACT_APP_ADAPTERS_HOST: https://backend.defihelper.io/adapters
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-release
          path: |
            build

  publish:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Download build-release
        uses: actions/download-artifact@v2
        with:
          name: build-release
          path: ./build

      - name: Publish dev
        if: github.event.release.prerelease == true
        run: |
          mkdir -pv $GITHUB_WORKSPACE
          cp -rf $GITHUB_WORKSPACE ~/$GITHUB_REPOSITORY-dev.new
          mv ~/$GITHUB_REPOSITORY-dev ~/$GITHUB_REPOSITORY-dev.old
          mv ~/$GITHUB_REPOSITORY-dev.new ~/$GITHUB_REPOSITORY-dev
          rm -rf ~/$GITHUB_REPOSITORY-dev.old

      - name: Publish stable
        if: github.event.release.prerelease == false
        run: |
          mkdir -pv $GITHUB_WORKSPACE
          cp -rf $GITHUB_WORKSPACE ~/$GITHUB_REPOSITORY.new
          mv ~/$GITHUB_REPOSITORY ~/$GITHUB_REPOSITORY.old
          mv ~/$GITHUB_REPOSITORY.new ~/$GITHUB_REPOSITORY
          rm -rf ~/$GITHUB_REPOSITORY.old

  cloudflare-purge:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Purge cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
